version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typescript"
        versions: [">=6.0.0"]
      - dependency-name: "@vitest/coverage-v8"
        versions: [">=2.0.0"]
      - dependency-name: "vitest"
        versions: [">=2.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore"
      include: "scope"
